### ISSUE TITLE
Understanding of the equations in dc motor

### ISSUE THREAD

**Issue by eshafeeqe** [nilseuropa/gazebo_ros_motors#10]
Hi, 

Thanks for open sourcing this project. I am trying to understand the equations used for modelling dc motor (shown below). Is there any documentation for understanding it more deeply. I saw a link to INSA Lyon, but it is broken now.

![Screenshot from 2022-06-20 17-32-28](https://user-images.githubusercontent.com/5008123/174563457-adb69440-1cfe-491f-9861-214a95163ccf.png)

**Comment by brunoda92** [comment]
Hi @eshafeeqe ! 
I had the same issue, but I found the current live link to INSA Lyon, here it is : [http://www.ctrl-elec.fr/ctrl-elec/motor-control/dc-motor-control/84-2/](url)
You can also check the file "[dc_motor_de.pdf](https://github.com/nilseuropa/gazebo_ros_motors/blob/master/doc/dc_motor_de.pdf)" which shows the actual discrete equations (same ones from your screenshot) that the plugin solves to find the current and velocity values in each instant. They are a little tough to read but the show better what's actually going on under the hood, since the continuous equations in the INSA Lyon link are not actually solved (as they are) by the plugin.

Hope it helps :)

**Comment by eshafeeqe** [comment]
@brunoda92 Thanks a lot for your reply, that cleared my doubt. I always thinking of solving this numerical way and never thought to solve analytically.
